# WrapIt! configuration file
# @see https://github.com/grasph/wrapit/blob/main/doc/config.md

module_name = "DGGRID"
cxx-std = "c++11"
veto = false

input = ["HEADER"]

include_dirs = [
    "DGGRID/src/apps/dggrid/",

    "DGGRID/src/lib/dglib/lib/",
    "DGGRID/src/lib/dglib/include",
    "DGGRID/src/lib/dglib/include/dglib",
    "DGGRID/src/lib/dglib/lib",
]
