module_name         = "DGGRID"
input               = [
    "param.cpp",
    "dggrid.cpp",
    "transform.cpp",
    "DgParamList.cpp"
] 
include_dirs        = [
    "DGGRID/src/apps/dggrid/",
    "DGGRID/src/lib/dglib/lib/"
]
cxx-std             = "c++11"